"""Initial schema and server

Revision ID: c0a4288ea36c
Revises: 
Create Date: 2121-02-16 22:01:54.291389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a4288ea36c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users = op.create_table('server',
    sa.Column('server', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('server_type', sa.String(255), nullable=False),
    sa.PrimaryKeyConstraint('server'),
    sa.UniqueConstraint('description'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server')
    # ### end Alembic commands ###
